### PR TITLE
Fix null children

### LINKED ISSUE #9: v1.0.1 throwing errors with empty children arrays?
I tried updating to 1.0.1 in my examples app, and my examples which bring in data via HTTP requests are throwing errors.

`TypeError: Cannot read property 'data' of null`

It seems that the updated driver isn't handling `null` or `[]` children as well?  Not sure if you changed any of that safety code, but both of my routes which start with an empty array are having problems.

In the snippet below, `results` begins life = `[]`:

``` javascript
  const vtree$ = state$
    .map(({results, loading}) =>
      h('div.page-wrapper', {key: `ghpage`, style: fadeInOutStyle}, [
        h('div.page.github-search-container', {}, [
          h('label.label', {}, 'Search Github Repos:'),
          h('input.field', {props: {type: 'text'}}),
          h('hr'),
          h('section.search-results', {}, results.map(resultView).concat(loading ? loadingSpinner() : null)),
        ]),
      ])
    )
```

Thanks for the new quick reference to the snabbdom modules, btw :+1: 

Hoping to try out the HTML driver soon.

### PR DESCRIPTION
**Pull request by TylorS**
Add test and fix children of `null` value

Closes #9

### CODE REVIEW

**Comment by TylorS** [comment]
@SkaterDad Does the test [here](https://github.com/TylorS/cycle-snabbdom/commit/30d918b9756074528a7118b2db8fab7f4c1509ed) seem sufficient for you?

**Comment by SkaterDad** [comment]
The code changes and test look like they should address my issue well. 

I'll be able to test them out later tonight I hope.

**Comment by TylorS** [comment]
Great, I'll merge and push a patch release whenever you're able to confirm.

**Comment by TylorS** [comment]
@SkaterDad I added some more tests and a hopefully the fix for your situation.

**Comment by SkaterDad** [comment]
@TylorS The new changes worked nicely :+1: 

Thanks for your quick response.

This must be the kind of situation which leads people to start using TypeScript or Elm... :laughing:

**Comment by TylorS** [comment]
FWIW, I plan to write this library in TypeScript (eventually).

**Comment by TylorS** [comment]
Going to merge and do a 1.0.2 release :+1:

**Pull request merged**
